jaffle_shop:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      filesystems:
        - fs: gcs
      threads: 24
      external_root: "gcs://{{ env_var('GCS_BUCKET_NAME') }}/data"
      